apiVersion: v1
kind: Namespace
metadata:
  name:  ns-posthub^^env^^
  labels:
    name: ns-posthub^^env^^

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-eventhub
  namespace: ns-posthub^^env^^
spec:
  selector:
    matchLabels:
      app: nats-eventhub
  template:
    metadata:
      labels:
        app: nats-eventhub
    spec:
      containers:
      - name: nats-eventhub
        # image: nats-streaming:0.25.6
        image: nats-streaming:0.24.0
        args: [
          '--port', '4222',
          '--http_port', '8222',
          '--hb_interval', '5s',      
          '--hb_timeout', '5s',       
          '--hb_fail_count', '2',     
          '--stan_debug', 
          '--cluster_id', 'posthubcluster'
        ]
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "2000Mi"
            cpu: "1500m"

---
kind: Service
apiVersion: v1
metadata:
  name:  nats-eventhub-service
  namespace: ns-posthub^^env^^
spec:
  selector:
    app:  nats-eventhub
  type:  ClusterIP
  ports:
  - name:  client
    port:  4222
    targetPort:  4222
    protocol: TCP
  - name:  monitoring
    port:  8222
    targetPort:  8222
    protocol: TCP